stages:
  - build
  - test

build-job:
  stage: build
  image: python:3.12-slim
  script:
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r cama_backend/requirements.txt
    - echo "Hello, $GITLAB_USER_LOGIN!"

run_tests:
  stage: test
  image: python:3.12-slim
  script:
    - pytest