# .gitlab-ci.yml

stages:
  - build
  - test
  - log

build_back_end:
  stage: build
  image: python:3.12-slim
  artifacts:
    paths:
      - cama_backend/tempenv
    expire_in: 2 hrs
    untracked: true
  cache:
    key: 'back_end'
    paths: 
      - cama_backend/tempenv
  script:
    - pip install virtualenv
    - cd cama_backend/
    - virtualenv tempenv
    - source tempenv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt

test_back_end:
  stage: test
  image: python:3.12-slim
  needs: ['build_back_end']
  script:
    - cd cama_backend/
    - source tempenv/bin/activate
    - pytest --cov=myapi tests/
    - coverage xml
  artifacts:
    paths:
      - coverage.xml    
log_back_end:
  stage: log
  needs: ['test_back_end']
  script:
    - cd cama_backend
    - python coverage.py
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    expire_in: 1 week