# Generated by Django 4.2.10 on 2024-04-23 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CamaUser',
            fields=[
                ('orc_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('organization', models.CharField(max_length=255, null=True)),
                ('nr_uploads', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EffectSizeType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Implementation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('implementor', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantDesign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('design', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskOfBias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rob', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyDesign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('design', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('study_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('study_year', models.IntegerField()),
                ('peer_reviewed', models.BooleanField()),
                ('authors', models.CharField(max_length=255)),
                ('doi', models.CharField(max_length=255)),
                ('abstract', models.CharField(max_length=3000)),
                ('keywords', models.CharField(max_length=255)),
                ('nr_downloads', models.IntegerField(default=0, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.category')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.country')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.camauser')),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('experiment_nr', models.AutoField(primary_key=True, serialize=False)),
                ('robins', models.CharField(max_length=255, null=True)),
                ('intensity_n', models.IntegerField(null=True)),
                ('duration_week', models.IntegerField(null=True)),
                ('frequency_n', models.IntegerField(null=True)),
                ('ni', models.IntegerField()),
                ('intervention', models.CharField(max_length=255)),
                ('intervention_op', models.CharField(max_length=255)),
                ('target_population', models.CharField(max_length=255)),
                ('mean_age', models.FloatField(null=True)),
                ('source', models.CharField(max_length=255, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.grade')),
                ('implemented', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.implementation')),
                ('participant_design', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.participantdesign')),
                ('risks', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.riskofbias')),
                ('study_design', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.studydesign')),
                ('study_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='myapi.study')),
            ],
            options={
                'unique_together': {('study_id', 'experiment_nr')},
            },
        ),
        migrations.CreateModel(
            name='EffectData',
            fields=[
                ('effect_size_number', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=255)),
                ('outcome', models.CharField(max_length=255)),
                ('outcome_full', models.CharField(max_length=255)),
                ('outcome_op', models.CharField(max_length=255)),
                ('gender_1', models.IntegerField(null=True)),
                ('gender_2', models.IntegerField(null=True)),
                ('gender_3', models.IntegerField(null=True)),
                ('d_var', models.FloatField(null=True)),
                ('d', models.FloatField(null=True)),
                ('f_stat', models.FloatField(null=True)),
                ('t', models.FloatField(null=True)),
                ('ri', models.FloatField(null=True)),
                ('icc', models.FloatField()),
                ('mean_age_1i', models.FloatField(null=True)),
                ('mean_age_2i', models.FloatField(null=True)),
                ('ai', models.IntegerField(null=True)),
                ('bi', models.IntegerField(null=True)),
                ('ci', models.IntegerField(null=True)),
                ('di', models.IntegerField(null=True)),
                ('sd1i', models.FloatField(null=True)),
                ('sd2i', models.FloatField(null=True)),
                ('n1i', models.FloatField(null=True)),
                ('n2i', models.FloatField(null=True)),
                ('m1i', models.FloatField(null=True)),
                ('m2i', models.FloatField(null=True)),
                ('approved', models.BooleanField(default=False)),
                ('effect_size_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.effectsizetype')),
                ('experiment_nr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='myapi.experiment')),
                ('test_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myapi.testtime')),
            ],
            options={
                'unique_together': {('effect_size_number', 'experiment_nr')},
            },
        ),
    ]
