# Generated by Django 4.2.10 on 2024-04-24 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camauser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='camauser',
            name='organization',
        ),
        migrations.AddField(
            model_name='effectdata',
            name='effect_size_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estype', to='myapi.effectsizetype'),
        ),
        migrations.AlterField(
            model_name='effectdata',
            name='experiment_nr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='myapi.experiment'),
        ),
        migrations.AlterField(
            model_name='effectdata',
            name='test_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='testtime', to='myapi.testtime'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agegrade', to='myapi.grade'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='implemented',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implementation', to='myapi.implementation'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='participant_design',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_design', to='myapi.participantdesign'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='risks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riskofbias', to='myapi.riskofbias'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='study_design',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_design', to='myapi.studydesign'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='study_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='myapi.study'),
        ),
        migrations.AlterField(
            model_name='study',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='myapi.category'),
        ),
        migrations.AlterField(
            model_name='study',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country', to='myapi.country'),
        ),
        migrations.AlterField(
            model_name='study',
            name='nr_downloads',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studies', to='myapi.camauser'),
        ),
    ]
