# Generated by Django 4.2.10 on 2024-04-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='effectdata',
            name='outcome',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='effectdata',
            name='outcome_full',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='effectdata',
            name='outcome_op',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='effectdata',
            name='ri',
            field=models.FloatField(null=True),
        ),
    ]
