# Generated by Django 4.2.10 on 2024-04-12 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='study',
            old_name='year',
            new_name='study_year',
        ),
        migrations.RenameField(
            model_name='year',
            old_name='year',
            new_name='study_year',
        ),
    ]
