# Generated by Django 4.2.10 on 2024-04-18 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_alter_experiment_study_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EffectSizeType',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TestTime',
            fields=[
                ('time', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='effectdata',
            unique_together={('effect_size_number', 'experiment_nr')},
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='gender_1',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='gender_2',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='outcome',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='outcome_full',
        ),
        migrations.AddField(
            model_name='effectdata',
            name='effect_size_type',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='effectdata',
            name='gender_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='effectdata',
            name='gender_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='effectdata',
            name='gender_3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='effectdata',
            name='mean_age_1i',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='effectdata',
            name='mean_age_2i',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='effectdata',
            name='test_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='intervention',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='intervention_op',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='mean_age',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='ni',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='source',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='target_population',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='participant_design',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myapi.participantdesign'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='risks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myapi.riskofbias'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='study_design',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myapi.studydesign'),
        ),
        migrations.AlterField(
            model_name='riskofbias',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='riskofbias',
            name='rob',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='riskofbias',
            name='robins',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='study_year',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Year',
        ),
        migrations.RemoveField(
            model_name='effectdata',
            name='mean_age',
        ),
        migrations.RemoveField(
            model_name='effectdata',
            name='ni',
        ),
        migrations.RemoveField(
            model_name='effectdata',
            name='study_id',
        ),
        migrations.AddField(
            model_name='effectdata',
            name='test_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myapi.testtime'),
        ),
    ]
