# Generated by Django 4.2.10 on 2024-04-23 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_alter_effectdata_experiment_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effectdata',
            name='effect_size_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.effectsizetype'),
        ),
    ]
