# Generated by Django 4.2.10 on 2024-04-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_effectsizetype_testtime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetPopulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=255)),
            ],
        ),
    ]
