# Generated by Django 4.2.10 on 2024-05-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_alter_experiment_grade_alter_experiment_implemented_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camauser',
            name='nr_uploads',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
