# Generated by Django 4.2.10 on 2024-05-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_alter_camauser_nr_uploads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camauser',
            name='nr_uploads',
            field=models.IntegerField(default=0),
        ),
    ]
