# Generated by Django 4.2.10 on 2024-05-17 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_alter_camauser_nr_uploads'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='forth',
            new_name='fourth',
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('k', 'first', 'second', 'third', 'fourth', 'fifth', 'sixth', 'seventh', 'eighth', 'ninth', 'tenth', 'eleventh', 'twelfth')},
        ),
    ]
